//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::True;

impl_payload! {
    /// Removes the profile photo of the bot. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Default, Clone, Serialize)]
    pub RemoveMyProfilePhoto (RemoveMyProfilePhotoSetters) => True {

    }
}
